import Head from "next/head"; 
import { Inter } from "@next/font/google";  
import CountDownTimer from "@/components/CountDown/CountDownTimer";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import CountDown from "@/components/CountDown/CountDown";   
import Banner from "@/components/Bannner/Bannner";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main> 
        <Navbar/>
        <Banner/>
        <CountDown/>
        <CountDownTimer/>
        <Footer/> 
      </main>
    </>
  );
}
